# Generated by Django 6.0.3 on 2026-05-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Marine', 'Marine Solutions'), ('Industrial', 'Industrial Systems'), ('Engineering', 'Engineering Supplies'), ('Construction', 'Construction Materials'), ('Chemicals', 'Chemicals & Maintenance')], max_length=100)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('pc', 'Piece'), ('kg', 'Kilograms'), ('m', 'Meters'), ('drum', 'Drums'), ('sheet', 'Sheet'), ('set', 'Set'), ('kit', 'Kit'), ('unit', 'Unit')], default='pcs', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_stock', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=10, help_text='Alert when stock hits this level')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Incoming/Received'), ('OUT', 'Outgoing/To Project')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('project_site', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
