# Generated by Django 6.0.3 on 2026-03-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('m', 'Meters'), ('drum', 'Drums')], default='pcs', max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Marine', 'Marine Solutions'), ('Industrial', 'Industrial Systems'), ('Engineering', 'Engineering Supplies'), ('Construction', 'Construction Materials'), ('Chemicals', 'Chemicals & Maintenance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
