# Generated by Django 6.0.3 on 2026-03-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_material_unit_alter_material_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('pc', 'Piece'), ('kg', 'Kilograms'), ('m', 'Meters'), ('drum', 'Drums'), ('sheet', 'Sheet')], default='pcs', max_length=10),
        ),
    ]
