# Generated by Django 6.0.3 on 2026-03-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_material_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='min_stock_level',
            field=models.IntegerField(default=10, help_text='Alert when stock hits this level'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('pc', 'Piece'), ('kg', 'Kilograms'), ('m', 'Meters'), ('drum', 'Drums'), ('sheet', 'Sheet'), ('set', 'Set'), ('kit', 'Kit')], default='pcs', max_length=10),
        ),
    ]
