# Generated by Django 6.0.3 on 2026-03-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_material_min_stock_level_alter_material_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('pc', 'Piece'), ('kg', 'Kilograms'), ('m', 'Meters'), ('drum', 'Drums'), ('sheet', 'Sheet'), ('set', 'Set'), ('kit', 'Kit'), ('unit', 'Unit')], default='pcs', max_length=10),
        ),
    ]
